// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: annotations/annotations.proto

package annotations

import (
	bson "github.com/rleszilm/genms-datalayer/pkg/annotations/bson"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comparator int32

const (
	Comparator_EQ  Comparator = 0
	Comparator_NE  Comparator = 1
	Comparator_GT  Comparator = 2
	Comparator_LT  Comparator = 3
	Comparator_GTE Comparator = 4
	Comparator_LTE Comparator = 5
)

// Enum value maps for Comparator.
var (
	Comparator_name = map[int32]string{
		0: "EQ",
		1: "NE",
		2: "GT",
		3: "LT",
		4: "GTE",
		5: "LTE",
	}
	Comparator_value = map[string]int32{
		"EQ":  0,
		"NE":  1,
		"GT":  2,
		"LT":  3,
		"GTE": 4,
		"LTE": 5,
	}
)

func (x Comparator) Enum() *Comparator {
	p := new(Comparator)
	*p = x
	return p
}

func (x Comparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Comparator) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_annotations_proto_enumTypes[0].Descriptor()
}

func (Comparator) Type() protoreflect.EnumType {
	return &file_annotations_annotations_proto_enumTypes[0]
}

func (x Comparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Comparator.Descriptor instead.
func (Comparator) EnumDescriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

type Datastore int32

const (
	Datastore_UndefinedDatastore Datastore = 0
	Datastore_Mongo              Datastore = 1
)

// Enum value maps for Datastore.
var (
	Datastore_name = map[int32]string{
		0: "UndefinedDatastore",
		1: "Mongo",
	}
	Datastore_value = map[string]int32{
		"UndefinedDatastore": 0,
		"Mongo":              1,
	}
)

func (x Datastore) Enum() *Datastore {
	p := new(Datastore)
	*p = x
	return p
}

func (x Datastore) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Datastore) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_annotations_proto_enumTypes[1].Descriptor()
}

func (Datastore) Type() protoreflect.EnumType {
	return &file_annotations_annotations_proto_enumTypes[1]
}

func (x Datastore) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Datastore.Descriptor instead.
func (Datastore) EnumDescriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{1}
}

type Generate int32

const (
	Generate_Skip      Generate = 0
	Generate_Implement Generate = 1
	Generate_Interface Generate = 2
)

// Enum value maps for Generate.
var (
	Generate_name = map[int32]string{
		0: "Skip",
		1: "Implement",
		2: "Interface",
	}
	Generate_value = map[string]int32{
		"Skip":      0,
		"Implement": 1,
		"Interface": 2,
	}
)

func (x Generate) Enum() *Generate {
	p := new(Generate)
	*p = x
	return p
}

func (x Generate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Generate) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_annotations_proto_enumTypes[2].Descriptor()
}

func (Generate) Type() protoreflect.EnumType {
	return &file_annotations_annotations_proto_enumTypes[2]
}

func (x Generate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Generate.Descriptor instead.
func (Generate) EnumDescriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{2}
}

type Query_Returns int32

const (
	Query_Many   Query_Returns = 0
	Query_Single Query_Returns = 1
	Query_Stream Query_Returns = 2
)

// Enum value maps for Query_Returns.
var (
	Query_Returns_name = map[int32]string{
		0: "Many",
		1: "Single",
		2: "Stream",
	}
	Query_Returns_value = map[string]int32{
		"Many":   0,
		"Single": 1,
		"Stream": 2,
	}
)

func (x Query_Returns) Enum() *Query_Returns {
	p := new(Query_Returns)
	*p = x
	return p
}

func (x Query_Returns) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Query_Returns) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_annotations_proto_enumTypes[3].Descriptor()
}

func (Query_Returns) Type() protoreflect.EnumType {
	return &file_annotations_annotations_proto_enumTypes[3]
}

func (x Query_Returns) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Query_Returns.Descriptor instead.
func (Query_Returns) EnumDescriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{0, 0}
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args     []*Query_Arg  `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Generate Generate      `protobuf:"varint,3,opt,name=generate,proto3,enum=genms.dal.Generate" json:"generate,omitempty"`
	Returns  Query_Returns `protobuf:"varint,4,opt,name=returns,proto3,enum=genms.dal.Query_Returns" json:"returns,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_annotations_annotations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_annotations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Query) GetArgs() []*Query_Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Query) GetGenerate() Generate {
	if x != nil {
		return x.Generate
	}
	return Generate_Skip
}

func (x *Query) GetReturns() Query_Returns {
	if x != nil {
		return x.Returns
	}
	return Query_Many
}

type Collection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datastores []Datastore `protobuf:"varint,1,rep,packed,name=datastores,proto3,enum=genms.dal.Datastore" json:"datastores,omitempty"`
	Queries    []*Query    `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	Generate   Generate    `protobuf:"varint,3,opt,name=generate,proto3,enum=genms.dal.Generate" json:"generate,omitempty"`
}

func (x *Collection) Reset() {
	*x = Collection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_annotations_annotations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_annotations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Collection) GetDatastores() []Datastore {
	if x != nil {
		return x.Datastores
	}
	return nil
}

func (x *Collection) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *Collection) GetGenerate() Generate {
	if x != nil {
		return x.Generate
	}
	return Generate_Skip
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ignore bool         `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Name   string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mongo  *Field_Mongo `protobuf:"bytes,3,opt,name=mongo,proto3" json:"mongo,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_annotations_annotations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_annotations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetMongo() *Field_Mongo {
	if x != nil {
		return x.Mongo
	}
	return nil
}

type Query_Arg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comparison Comparator `protobuf:"varint,2,opt,name=comparison,proto3,enum=genms.dal.Comparator" json:"comparison,omitempty"`
}

func (x *Query_Arg) Reset() {
	*x = Query_Arg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_annotations_annotations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Arg) ProtoMessage() {}

func (x *Query_Arg) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_annotations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Arg.ProtoReflect.Descriptor instead.
func (*Query_Arg) Descriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Query_Arg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Query_Arg) GetComparison() Comparator {
	if x != nil {
		return x.Comparison
	}
	return Comparator_EQ
}

type Field_Mongo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Primitive bson.Primitive `protobuf:"varint,2,opt,name=primitive,proto3,enum=genms.dal.bson.Primitive" json:"primitive,omitempty"`
}

func (x *Field_Mongo) Reset() {
	*x = Field_Mongo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_annotations_annotations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field_Mongo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field_Mongo) ProtoMessage() {}

func (x *Field_Mongo) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_annotations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field_Mongo.ProtoReflect.Descriptor instead.
func (*Field_Mongo) Descriptor() ([]byte, []int) {
	return file_annotations_annotations_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Field_Mongo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field_Mongo) GetPrimitive() bson.Primitive {
	if x != nil {
		return x.Primitive
	}
	return bson.Primitive(0)
}

var file_annotations_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Collection)(nil),
		Field:         51001,
		Name:          "genms.dal.message_options",
		Tag:           "bytes,51001,opt,name=message_options",
		Filename:      "annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Field)(nil),
		Field:         51001,
		Name:          "genms.dal.field_options",
		Tag:           "bytes,51001,opt,name=field_options",
		Filename:      "annotations/annotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional genms.dal.Collection message_options = 51001;
	E_MessageOptions = &file_annotations_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional genms.dal.Field field_options = 51001;
	E_FieldOptions = &file_annotations_annotations_proto_extTypes[1]
)

var File_annotations_annotations_proto protoreflect.FileDescriptor

var file_annotations_annotations_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x62, 0x73, 0x6f, 0x6e, 0x2f, 0x62,
	0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x02, 0x0a, 0x05, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61,
	0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x12, 0x2f, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x52, 0x07, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x1a, 0x50, 0x0a, 0x03, 0x41, 0x72, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61,
	0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x6e, 0x79, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x10, 0x02, 0x22, 0x9f, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73,
	0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x0a,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x71, 0x75,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65,
	0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x07, 0x71,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73,
	0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x08, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x4d,
	0x6f, 0x6e, 0x67, 0x6f, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x1a, 0x54, 0x0a, 0x05, 0x4d,
	0x6f, 0x6e, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x67, 0x65,
	0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x62, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69,
	0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x2a, 0x3e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x06, 0x0a, 0x02, 0x45, 0x51, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x45, 0x10, 0x01, 0x12,
	0x06, 0x0a, 0x02, 0x47, 0x54, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x54, 0x10, 0x03, 0x12,
	0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10,
	0x05, 0x2a, 0x2e, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x16,
	0x0a, 0x12, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x10,
	0x01, 0x2a, 0x32, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x53, 0x6b, 0x69, 0x70, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6d, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x10, 0x02, 0x3a, 0x61, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x8e, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x56, 0x0a, 0x0d, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x8e, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x6c, 0x65, 0x73, 0x7a, 0x69, 0x6c, 0x6d, 0x2f, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2d, 0x64, 0x61,
	0x74, 0x61, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_annotations_annotations_proto_rawDescOnce sync.Once
	file_annotations_annotations_proto_rawDescData = file_annotations_annotations_proto_rawDesc
)

func file_annotations_annotations_proto_rawDescGZIP() []byte {
	file_annotations_annotations_proto_rawDescOnce.Do(func() {
		file_annotations_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_annotations_annotations_proto_rawDescData)
	})
	return file_annotations_annotations_proto_rawDescData
}

var file_annotations_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_annotations_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_annotations_annotations_proto_goTypes = []interface{}{
	(Comparator)(0),                     // 0: genms.dal.Comparator
	(Datastore)(0),                      // 1: genms.dal.Datastore
	(Generate)(0),                       // 2: genms.dal.Generate
	(Query_Returns)(0),                  // 3: genms.dal.Query.Returns
	(*Query)(nil),                       // 4: genms.dal.Query
	(*Collection)(nil),                  // 5: genms.dal.Collection
	(*Field)(nil),                       // 6: genms.dal.Field
	(*Query_Arg)(nil),                   // 7: genms.dal.Query.Arg
	(*Field_Mongo)(nil),                 // 8: genms.dal.Field.Mongo
	(bson.Primitive)(0),                 // 9: genms.dal.bson.Primitive
	(*descriptorpb.MessageOptions)(nil), // 10: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 11: google.protobuf.FieldOptions
}
var file_annotations_annotations_proto_depIdxs = []int32{
	7,  // 0: genms.dal.Query.args:type_name -> genms.dal.Query.Arg
	2,  // 1: genms.dal.Query.generate:type_name -> genms.dal.Generate
	3,  // 2: genms.dal.Query.returns:type_name -> genms.dal.Query.Returns
	1,  // 3: genms.dal.Collection.datastores:type_name -> genms.dal.Datastore
	4,  // 4: genms.dal.Collection.queries:type_name -> genms.dal.Query
	2,  // 5: genms.dal.Collection.generate:type_name -> genms.dal.Generate
	8,  // 6: genms.dal.Field.mongo:type_name -> genms.dal.Field.Mongo
	0,  // 7: genms.dal.Query.Arg.comparison:type_name -> genms.dal.Comparator
	9,  // 8: genms.dal.Field.Mongo.primitive:type_name -> genms.dal.bson.Primitive
	10, // 9: genms.dal.message_options:extendee -> google.protobuf.MessageOptions
	11, // 10: genms.dal.field_options:extendee -> google.protobuf.FieldOptions
	5,  // 11: genms.dal.message_options:type_name -> genms.dal.Collection
	6,  // 12: genms.dal.field_options:type_name -> genms.dal.Field
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	11, // [11:13] is the sub-list for extension type_name
	9,  // [9:11] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_annotations_annotations_proto_init() }
func file_annotations_annotations_proto_init() {
	if File_annotations_annotations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_annotations_annotations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_annotations_annotations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Collection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_annotations_annotations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_annotations_annotations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Arg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_annotations_annotations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field_Mongo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_annotations_annotations_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_annotations_annotations_proto_goTypes,
		DependencyIndexes: file_annotations_annotations_proto_depIdxs,
		EnumInfos:         file_annotations_annotations_proto_enumTypes,
		MessageInfos:      file_annotations_annotations_proto_msgTypes,
		ExtensionInfos:    file_annotations_annotations_proto_extTypes,
	}.Build()
	File_annotations_annotations_proto = out.File
	file_annotations_annotations_proto_rawDesc = nil
	file_annotations_annotations_proto_goTypes = nil
	file_annotations_annotations_proto_depIdxs = nil
}
