// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: annotations/bson/bson.proto

package bson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Primitive int32

const (
	Primitive_UndefinedPrimitive Primitive = 0
	Primitive_Datetime           Primitive = 1
	Primitive_Decimal128         Primitive = 2
	Primitive_ObjectID           Primitive = 3
	Primitive_Timestamp          Primitive = 4
)

// Enum value maps for Primitive.
var (
	Primitive_name = map[int32]string{
		0: "UndefinedPrimitive",
		1: "Datetime",
		2: "Decimal128",
		3: "ObjectID",
		4: "Timestamp",
	}
	Primitive_value = map[string]int32{
		"UndefinedPrimitive": 0,
		"Datetime":           1,
		"Decimal128":         2,
		"ObjectID":           3,
		"Timestamp":          4,
	}
)

func (x Primitive) Enum() *Primitive {
	p := new(Primitive)
	*p = x
	return p
}

func (x Primitive) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Primitive) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_bson_bson_proto_enumTypes[0].Descriptor()
}

func (Primitive) Type() protoreflect.EnumType {
	return &file_annotations_bson_bson_proto_enumTypes[0]
}

func (x Primitive) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Primitive.Descriptor instead.
func (Primitive) EnumDescriptor() ([]byte, []int) {
	return file_annotations_bson_bson_proto_rawDescGZIP(), []int{0}
}

var File_annotations_bson_bson_proto protoreflect.FileDescriptor

var file_annotations_bson_bson_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x62, 0x73,
	0x6f, 0x6e, 0x2f, 0x62, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67,
	0x65, 0x6e, 0x6d, 0x73, 0x2e, 0x64, 0x61, 0x6c, 0x2e, 0x62, 0x73, 0x6f, 0x6e, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x5e, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x12,
	0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x31, 0x32, 0x38,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x10, 0x03,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x10, 0x04, 0x42,
	0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6c,
	0x65, 0x73, 0x7a, 0x69, 0x6c, 0x6d, 0x2f, 0x67, 0x65, 0x6e, 0x6d, 0x73, 0x2d, 0x64, 0x61, 0x74,
	0x61, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x62, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_annotations_bson_bson_proto_rawDescOnce sync.Once
	file_annotations_bson_bson_proto_rawDescData = file_annotations_bson_bson_proto_rawDesc
)

func file_annotations_bson_bson_proto_rawDescGZIP() []byte {
	file_annotations_bson_bson_proto_rawDescOnce.Do(func() {
		file_annotations_bson_bson_proto_rawDescData = protoimpl.X.CompressGZIP(file_annotations_bson_bson_proto_rawDescData)
	})
	return file_annotations_bson_bson_proto_rawDescData
}

var file_annotations_bson_bson_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_annotations_bson_bson_proto_goTypes = []interface{}{
	(Primitive)(0), // 0: genms.dal.bson.Primitive
}
var file_annotations_bson_bson_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_annotations_bson_bson_proto_init() }
func file_annotations_bson_bson_proto_init() {
	if File_annotations_bson_bson_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_annotations_bson_bson_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_annotations_bson_bson_proto_goTypes,
		DependencyIndexes: file_annotations_bson_bson_proto_depIdxs,
		EnumInfos:         file_annotations_bson_bson_proto_enumTypes,
	}.Build()
	File_annotations_bson_bson_proto = out.File
	file_annotations_bson_bson_proto_rawDesc = nil
	file_annotations_bson_bson_proto_goTypes = nil
	file_annotations_bson_bson_proto_depIdxs = nil
}
