// Package dalmongo is generated by protoc-gen-go-dal. *DO NOT EDIT*
package dalmongo

import (
	time "time"
)

// $.G.Message.GoKind }}Config is a struct that can be used to configure a AllCollection
type AllConfig struct {
	Name       string        `envconfig:"name" default:"dal-all"`
	Database   string        `envconfig:"database" default:"vvv-repl"`
	Collection string        `envconfig:"collection" default:"all"`
	Timeout    time.Duration `envconfig:"timeout" default:"5s"`
}

/*

All All
ignore || name || query name || go kind || qualified go kind || qualified mongo kind
false || SDouble || SDouble || float64 || All_SDouble || double
false || SFloat || SFloat || float32 || All_SFloat || float
false || SInt32 || SInt32 || int32 || All_SInt32 || int32
false || SInt64 || SInt64 || int64 || All_SInt64 || int64
false || SUint32 || SUint32 || uint32 || All_SUint32 || uint32
false || SUint64 || SUint64 || uint64 || All_SUint64 || uint64
false || SSint32 || SSint32 || int32 || All_SSint32 || sint32
false || SSint64 || SSint64 || int64 || All_SSint64 || sint64
false || SFixed32 || SFixed32 || uint32 || All_SFixed32 || fixed32
false || SFixed64 || SFixed64 || uint64 || All_SFixed64 || fixed64
false || SSfixed32 || SSfixed32 || int32 || All_SSfixed32 || sfixed32
false || SSfixed64 || SSfixed64 || int64 || All_SSfixed64 || sfixed64
false || SBool || SBool || bool || All_SBool || bool
false || SString || SString || string || All_SString || string
false || SBytes || SBytes || []byte || All_SBytes || bytes
false || EConst || EConst || AllConst || All_EConst || enum
false || MSubmessage || MSubmessage || *AllSubMessage || All_MSubmessage || message
false || MDouble || MDouble || []float64 || All_MDouble || double
false || MStringDouble || MStringDouble || map[string]float64 || All_MStringDouble || message
false || OneSString || OneSString || *string || All_OneSString || string
false || OneMSubmessage || OneMSubmessage || *AllSubMessage || All_OneMSubmessage || message
false || OsDouble || OsDouble || *float64 || All_OsDouble || double
false || OsFloat || OsFloat || *float32 || All_OsFloat || float
false || OsInt32 || OsInt32 || *int32 || All_OsInt32 || int32
false || OsInt64 || OsInt64 || *int64 || All_OsInt64 || int64
false || OsUint32 || OsUint32 || *uint32 || All_OsUint32 || uint32
false || OsUint64 || OsUint64 || *uint64 || All_OsUint64 || uint64
false || OsSint32 || OsSint32 || *int32 || All_OsSint32 || sint32
false || OsSint64 || OsSint64 || *int64 || All_OsSint64 || sint64
false || OsFixed32 || OsFixed32 || *uint32 || All_OsFixed32 || fixed32
false || OsFixed64 || OsFixed64 || *uint64 || All_OsFixed64 || fixed64
false || OsSfixed32 || OsSfixed32 || *int32 || All_OsSfixed32 || sfixed32
false || OsSfixed64 || OsSfixed64 || *int64 || All_OsSfixed64 || sfixed64
false || OsBool || OsBool || *bool || All_OsBool || bool
false || OsString || OsString || *string || All_OsString || string
false || OsBytes || OsBytes || []byte || All_OsBytes || bytes
false || OeConst || OeConst || *AllConst || All_OeConst || enum
false || OmSubmessage || OmSubmessage || *AllSubMessage || All_OmSubmessage || message
*/
